spring.datasource.url=jdbc:postgresql://localhost:5432/FinApp
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=financeprojectboard@gmail.com
spring.mail.password=wrlyuzrdkovkovgb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.timeout=15m

spring.data.redis.host=localhost
spring.data.redis.port=6379


jwt.secret="24x5Brv96DYB7KoStYaHH4WrRICaDSx0+C3IypTu1ir14DwnIjEp11/dMKJwuy88WfyjOM7URrC20GGsLA4gBQ=="
jwt.jwtExpirationMs=900000
#15min
jwt.refreshExpirationMs=604800000
#7days


#spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.hibernate=debug














